spring.application.name=Issue-Tracker
server.port=8081

app.message=Welcome to Spring Boot Config

spring.datasource.url=jdbc:postgresql://localhost:5432/issue_tracker_flyway_db
spring.datasource.username=postgres
spring.datasource.password=154545!%$%$%

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
